# Generated by Django 2.1.2 on 2018-11-02 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='earning',
            name='account',
            field=models.ForeignKey(help_text='used when calculating per account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tms.Account'),
        ),
        migrations.AddField(
            model_name='earning',
            name='client',
            field=models.ForeignKey(help_text='used when calculating per client', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tms.Client'),
        ),
        migrations.AddField(
            model_name='earning',
            name='user',
            field=models.ForeignKey(help_text='used when calculating per user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='earning',
            name='project',
            field=models.ForeignKey(help_text='used when calculating per project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tms.Project'),
        ),
    ]
