# Generated by Django 2.1.2 on 2019-05-13 04:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_squashed_0008_auto_20190513_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='booking year')),
                ('month', models.IntegerField(help_text='booking month')),
                ('status', models.CharField(choices=[('CL', 'Calculated'), ('AC', 'Active')], help_text='active or calculated', max_length=2)),
                ('weeks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='aggregation of week numbers for month', size=None)),
                ('booked_date', models.DateTimeField(help_text='date when accounting month is finished', null=True)),
                ('comments', models.TextField(help_text='comments', max_length=1024, null=True)),
                ('done_by', models.ForeignKey(help_text='user who calculated whole', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
