# Generated by Django 2.1.2 on 2019-06-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiAccount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='is_payment_account',
            field=models.BooleanField(default=False, help_text='Indicates whether it is payment gateway account or not'),
        ),
        migrations.AddField(
            model_name='project',
            name='share_percent',
            field=models.FloatField(help_text='Percent that is used when calculating outsourcing project profit', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(help_text='Email', max_length=30),
        ),
    ]
