# Generated by Django 2.1.2 on 2019-02-05 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='user_in_charge',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='account',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='client',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='earn_type',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='status',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='user',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='week_year',
        ),
        migrations.AddField(
            model_name='earning',
            name='approved_by',
            field=models.ForeignKey(help_text='user who confirmed paying', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='earning',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Confirm paying', null=True),
        ),
    ]
