# Generated by Django 2.1.2 on 2019-07-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_auto_20190729_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='weeks',
        ),
    ]
