# Generated by Django 2.2.4 on 2019-09-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_remove_book_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='finance_account',
            field=models.ForeignKey(help_text='actual financial account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_account', to='tms.Account'),
        ),
        migrations.CreateModel(
            name='AccountFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(help_text='date when deleted', null=True)),
                ('email_account', models.ForeignKey(help_text='email account mapped', on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to='tms.Account')),
                ('financial_account', models.ForeignKey(help_text='financial account', on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to='tms.Account')),
            ],
        ),
    ]
