# Generated by Django 2.2.4 on 2019-09-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_auto_20190909_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(help_text='reward type', max_length=32)),
                ('taken_id', models.IntegerField(help_text='id of taken. team_id when "team", user_id when "member"')),
                ('rewarded_date', models.DateField(help_text='rewarded date')),
                ('initial_amount', models.FloatField(help_text='the remaining amount after rewarding')),
            ],
        ),
    ]
